[build]
  functions = "netlify/functions"
  publish = "dist"
  
[dev]
  command = "npm run dev"
  
# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Configure secrets scanning to omit false positives
  SECRETS_SCAN_OMIT_KEYS = "VITE_AI_FEATURES_ENABLED"
  
# Configure build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
  output_path = "reports/lighthouse"

# Enable bundling for improved performance
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
  
# Add more specific headers for caching and security
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/.netlify/functions/websocket"
  to = "/.netlify/functions/websocket"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[functions.websocket]
  memory = 1024
  maxDuration = 30 