[build]
  command = "npm run build"
  publish = "dist"
  
[dev]
  command = "npm run dev"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  
# Enable bundling for improved performance
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 